version: 0.2

phases:
  install:
    commands:
      - pip install yamllint
      - pip install awscli
      - pip install taskcat
  build:
    commands:
      - ls
      - /usr/local/bin/yamllint job_cloud_formation.yml
