version: 0.2

phases:
  install:
    commands:
      - pip install yamllint
      - pip install awscli
      - pip install taskcat
      - pip install cfn-lint
  build:
    commands:
      - cfn-lint job_cloud_formation.yml
      - /usr/local/bin/yamllint job_cloud_formation.yml
